name: Update README cards

# https://github.com/marketplace/actions/github-readme-stats-action
# https://github.com/Othmane-ElAlami/GitHub-ReadMe-Stats?tab=readme-ov-file#all-demos
# (https://github-readme-stats.vercel.app/api?username=ax-sh&show_icons=true&theme=merko&count_private=true)
# (https://github-readme-stats.vercel.app/api/top-langs/?username=ax-sh&theme=merko&layout=compact&hide=html,mdx,jupyter%20notebook)
on:
  push:
    branches:
      - main # or whatever branch(es) you want
      - master # or whatever branch(es) you want
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=merko&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=pie&show_icons=true&theme=merko&hide=html,mdx,jupyter%20notebook
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Generate pin card
      #        uses: readme-tools/github-readme-stats-action@v1
      #        with:
      #          card: pin
      #          options: username=readme-tools&repo=github-readme-stats
      #          path: profile/pin-readme-tools-github-readme-stats.svg
      #          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
